### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by planetis-m** [piesku/goodluck#34]
Hello friends,

Just wanted to say thank you for your effort at evolving this project and making it accessible to everyone, it is very appreciated! Your breakout clone specifically has helped me in understanding and writing games.

Since I have never written code in Typescript, I am using my programming language [Nim](nim-lang.org/). Your code is clearly written and had almost no trouble rewriting it to Nim.
Its been over a month but made great progress at my [repo](https://github.com/b3liever/breakout-ecs).

 I have also made changes you might be interested in incorporating back to this project. Specifically the [slotmap](https://github.com/b3liever/breakout-ecs/blob/master/registry.nim) and [sparseset](https://github.com/b3liever/breakout-ecs/blob/master/registry.nim) data structures. I would also like to implement a sorting system before the transformation, but I am not sure how would that work.

Tell me what you think and again thank you!

Antonis

**Comment by stasm** [comment]
Hey @b3liever, thank you for the kind words and for sharing your work with us! It looks amazing. I'll have a closer look tonight and I'll be back with more things to say :)

**Comment by stasm** [comment]
Alright, I'm back :) I read skypjack's series on ECS (something I meant to do for a long time). I also learned a bit of Nim so that I could follow your code with more ease. Once again, thanks for telling us about your effort. I means a lot to see other developers create something cool based on Goodluck!

I took notes while reading your code. I'd like to prefix them by saying that I don't know Nim and that my programming experience is mostly in managed languages. I've also only worked on small gamedev projects: 5-minute-long games and experiments where larger-scale problem don't exist. I don't have AAA experience; I imagine the performance requirements vastly differ there.

### Hierarchy

I like that you made Hierarchy its own component. I think it's elegant in terms of the ECS design and also nicely solves the memory management problem by using a linked list to store the children. I tried adding a separate component for parent-child relationships early on in Goodluck too (even before the first commit), but ultimately I decided it wasn't worth it in a language like JS/TS, where it's possible to use an array to store child ids, no matter how many children there are (since arrays are always dynamically-sized in JS).

Another reason why I merged transforms and hierarchies into one component was to reduce the total number of components. Since we're using bitsets as entity signatures and JS only supports bitwise operations on 32-bit integers (despite all numbers being 64-bit floats!), we're limited to 32 components. It's worth adding that so far I've never run into this limitation; I think that for small-scoped games like _Backcountry_ this number is enough. `Transform` is such a basic component that I imagine virtually all projects will need it; same with `Render`. That leaves 30 more components to implement the entire game logic. I didn't want to make it 29 by adding `Hierarchy`. The same can be said about `Transform.Dirty` which I saw you implemented as its own component. Here as well I'd call your approach more _pure_, while ours is more _pragmatic_ :) BTW I really like how you leveraged Nim's `set` to solve the same problem we solved with bitsets and bitmasks!

### Sparse Sets

This is an interesting data structure for ECS, thanks for sharing. As far as optimizing ECS goes, I've worked with Unity's archetypes before, but I haven't had a chance to use sparse sets. I like how simple they actually are and how they can improve data locality and CPU caching.

I'd like to try it out in Goodluck at some point. It's hard for me to predict the impact on performance given that the memory in JS is managed by the VM, but after reading [this blog post](https://medium.com/walkme-engineering/memory-in-javascript-beyond-leaks-8c1d697c655c) I'm really curious.

There's something I don't fully understand in your codebase. It looks like you only use a sparse set for `Game.world` (called `Game.World.Signature` in TS), while the storage for all component data is actually just `seq`. Wouldn't you also need to use `Storage` for all components to fully leverage the properties of sparse sets?

```nim
Game* = object
      world*: Storage[set[HasComponent]]
      entities*: Registry
      # ...
      collide*: seq[Collide]
      current*: seq[Current]
      draw2d*: seq[Draw2d]
      fade*: seq[Fade]
      hierarchy*: seq[Hierarchy]
      move*: seq[Move]
      previous*: seq[Previous]
      shake*: seq[Shake]
      transform*: seq[Transform2d]
```

Reading skypjack's [Part 2](https://skypjack.github.io/2019-03-07-ecs-baf-part-2/), it also seems like iterating over entities when using sparse sets could be refactored too. Rather than enumerate `world.pairs` and check signatures against the `Query`, skypjack suggests iterating over the dense array with the data for the component which is present on the fewest entities. This eliminates the need to iterate over all entities in the world. Have you considered this approach?

### Slot map

Another interesting data structure, thanks! The `O(1)` insertion sounds great, although from my experience creating new entities is rare enough that iterating over `World.Signature` is usually fine. I suspect that in the Breakout clone entity creation is more common than usual because particles are implemented as new entities. I think that the best solution for that problem would be to add a proper particle system, in which the emitter is a single entity.

### Fixed timestep

Backcountry [used to have a fixed-step loop](https://github.com/piesku/backcountry/commit/9914ccc), too, but we removed it to save a few bytes. I've always thought of fixed timestep as smaller as the frame delta, probably because I assumed that the primary use-case was physics integration. Your code made me realize that it can also be longer than the frame delta. I absolutely love your `sysIntrpl2d` as the solution to `sysTransform2d` running less frequently than `render`! I would like to add an example to Goodluck that uses it. Plus, I think it has potential to be useful in networking code. Great stuff.

Note to self: for best results in 3D, I _think_ that `sysIntrpl2d` would also need to compose an intermediate world-space transformation matrix  from the interpolated values of world position, rotation and scale. That's because OpenGL expects matrices as uniform values anyways.

### Sorting

You mentioned that you'd like to implement sorting before composing matrices in `sysTransform2d`. I haven't tried it myself but I remember reading an [article on how Autodesk Stingray solved it](http://bitsquid.blogspot.com/2014/10/building-data-oriented-entity-system.html). The whole blog is a gamedev-related treasure trove. 

### Code layout

- I like how you combined blueprints and scenes into a single file. I think they're conceptually close.
- I also like how mixins are separate from component type definitions. We didn't do it in TS to avoid too much boilerplate. In [breakoutc](https://github.com/stasm/breakoutc), OTOH, I _had_ to do it to avoid cyclic header includes.

HTH, and _good luck_!

**Comment by planetis-m** [comment]
I will go through all your points and do tests and benchmarks, thanks for the articles and I will get back to you!

**Comment by planetis-m** [comment]
Hi sorry for the late update, the project stalled during the summer and
when I returned to it, there where more bugs left to fix. So here is a summary:

# Interpolation system got merged with sysDraw2d

Reason was to free a bit for an extra component and avoid unnecessarily storing
interpolated transforms in a `Current` component, which is also badly named since
it lags behind present game update.
Cons: system `draw2d` is coupled with interpolation logic, meaning it can be used
to draw an ui for example. Not sure if that's a problem.

# New component HasFresh to signal a newly created entity

This fixes a nasty visual bug, where new entities would appear moving from the top
of the screen for a couple of frames. This is because of the interpolated rendering,
and the fix is to hide the entity for a couple of game updates. I have seen you choose
to run `sysTransform` twice instead, to fix a similar issue. Not sure which is best.

`HasDirty` and `HasFresh` can be both bools if you would like to save

# Singleton components don't use an array

`Fade` is one and it's stored in a unique pointer. Benefits are obvious.

# Non continuous rendering

In the game loop the flag `isUpdated` guards rendering if the game hasn't updated at least once.
This fixed the jittery motion (again related to interpolated rendering).
Not sure if that causes other issues but it seemed the most efficient way to fix the bug. 

# Only world.Signature is stored in a slot map

Actually In a benchmark I did, using sparse sets for everything, is 10% faster. The catch is my implementation
uses stack fixed-size arrays for storing `sparseToPacked` and `packedToSparse` mappings
(inside the implementation of a sparse set), which means for enough components and `maxEntities` it will
overflow the stack. I think the difference will become insignificant if they are placed on the heap
due to double pointer chasing.

# Other

I had a hard time implementing sorting but I will try again
I also tried what you are suggesting regarding iterating over entities and it seemed to
cumbersome to implement and would complicate everything further, I like the current design a lot better.

**Comment by planetis-m** [comment]
Hi, small update, sorting was implemented. Proper comparison [proc](https://gist.github.com/planetis-m/8c3782cb520e843127a3350e330cdea9) (as suggested by [ECS back and forth](https://skypjack.github.io/2019-08-20-ecs-baf-part-4-insights/)) for Hierarchies turns out to be recursive, or maybe am I thinking it wrong?

However using selection sort and simple [check](https://github.com/planetis-m/breakout-ecs/blob/1f5417ec317b1e6e313f27afa8b81f04aceb162c/systems/transform2d.nim#L40) produces correct results.

Doing "partial" sorting like in the [link](http://bitsquid.blogspot.com/2014/10/building-data-oriented-entity-system.html) you posted doesn't cover this corner case: |child|parent|grand-parent|

Btw benchmarking with made up data that look like hierarchies showed that indeed insertion sort was orders of magnitude faster than selection sort.

**Comment by planetis-m** [comment]
Hmm I wonder how it compares with your [approach](https://github.com/piesku/goodluck/pull/51)
